name: Node.js Backend CI

on:
  push:
    branches: [ "master" ]   # Tu repo usa "master", no "main"
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: npm install

      # Si no tienes script de build, no pasa nada.
      - name: Build or check app
        run: npm run build || echo "No build script found"

      # Opcional: puedes agregar este paso si quieres comprobar que inicia sin errores
      # - name: Start server (health check)
      #   run: node server.js || echo "Server started successfully"
